// Generated by CoffeeScript 1.4.0
(function() {

  $.fn.tumblerSlideViewer = function(config) {
    var $this, $winHeight, $winWifth, addTimer, bgChange, bodyBg, changeImage, flag, jsonLoader, link, now, num, onResizeHandler, options, photos, removeTimer, shuffle, shuffleFlag, size, slide, slideTime, slideTimer, url;
    $this = this;
    num = 10;
    now = 0;
    url = '';
    photos = [];
    link = [];
    slideTimer = null;
    slideTime = 0;
    size = 1200;
    flag = true;
    bodyBg = false;
    shuffleFlag = false;
    options = $.extend({
      url: '',
      slidetime: 3000,
      length: 10,
      shuffle: false
    }, config);
    if (options.url === '') {
      return false;
    }
    if ($this.get()[0].tagName === 'BODY') {
      bodyBg = true;
    }
    num = options.length;
    slideTime = options.slidetime;
    url = options.url + '/api/read/json?num=' + num + '&type=photo';
    shuffleFlag = options.shuffle;
    onResizeHandler = function() {
      var $winHeight, $winWidth;
      $winWidth = $(window).width();
      $winHeight = $(window).height();
      return $('.fitBg').css({
        'width': $winWidth + 'px',
        'height': $winHeight + 'px'
      });
    };
    addTimer = function() {
      return slideTimer = setInterval(slide, slideTime);
    };
    removeTimer = function() {
      return clearInterval(slideTimer);
    };
    shuffle = function(array) {
      var i, j, t;
      i = array.length;
      while (i) {
        j = Math.floor(Math.random() * i);
        t = array[--i];
        array[i] = array[j];
        array[j] = t;
      }
      return array;
    };
    bgChange = function() {
      var n;
      n = now + 1;
      if (n === num) {
        n = 0;
      }
      if (now % 2) {
        return $('#frontBg').css({
          'background': 'url(' + photos[n] + ') no-repeat center center fixed'
        });
      } else {
        return $('#backBg').css({
          'background': 'url(' + photos[n] + ') no-repeat center center fixed'
        });
      }
    };
    changeImage = function() {
      if (flag) {
        $('#frontBg').fadeIn(0);
        return $('#backBg').fadeOut(0, bgChange);
      } else {
        $('#frontBg').fadeOut(0);
        return $('#backBg').fadeIn(0, bgChange);
      }
    };
    slide = function() {
      now++;
      if (now === num) {
        now = 0;
      }
      if (bodyBg) {
        flag = !flag;
        return changeImage();
      } else {
        $('.tumblerImage').stop().fadeOut(1000);
        return $this.find('div').eq(now).stop().fadeIn(1000);
      }
    };
    if (bodyBg) {
      size = 1200;
      $this.css({
        'overflow': 'hidden'
      }).prepend('<div class="fitBg" id="frontBg"></div><div class="fitBg" id="backBg"></div>');
      $winWifth = 0;
      $winHeight = 0;
      $(window).resize(onResizeHandler);
      onResizeHandler();
    } else {
      if ($this.width() < 75) {
        size = 75;
      }
      if ($this.width() >= 75) {
        size = 100;
      }
      if ($this.width() >= 100) {
        size = 250;
      }
      if ($this.width() >= 250) {
        size = 400;
      }
      if ($this.width() >= 400) {
        size = 500;
      }
      if ($this.width() >= 500) {
        size = 1200;
      }
    }
    jsonLoader = function() {
      return $.ajax({
        type: 'GET',
        url: url,
        dataType: 'jsonp',
        success: function(data) {
          var i, _i, _j;
          if (shuffleFlag === true) {
            data = {};
            data.posts = shuffle(data.posts);
          }
          if (bodyBg) {
            for (i = _i = 0; 0 <= num ? _i <= num : _i >= num; i = 0 <= num ? ++_i : --_i) {
              if (data.posts[i] !== void 0) {
                photos.push(data.posts[i]["photo-url-1280"]);
              }
            }
            $('#frontBg').css({
              'background': 'url(' + photos[0] + ') no-repeat center center fixed'
            });
            $('#backBg').hide().css({
              'background': 'url(' + photos[1] + ') no-repeat center center fixed'
            });
            return $('.fitBg').css({
              'position': 'fixed',
              'top': '0',
              'left': '0',
              '-webkit-background-size': 'cover',
              '-moz-background-size': 'cover',
              '-o-background-size': 'cover',
              'background-size': 'cover'
            });
          } else {
            for (i = _j = 0; 0 <= num ? _j <= num : _j >= num; i = 0 <= num ? ++_j : --_j) {
              photos.push(data.posts[i]["photo-url-" + size]);
              links.push(data.posts[i]["url-with-slug"]);
              $this.prepend('<div class="tumblerImage">' + '<a href="' + links[i] + '" target="_blank">' + '<img class="tumblerImg" src="' + photos[i] + '" width="' + $this.width() + '" />' + '</a>' + '</div>');
            }
            $('.tumblerImage').css({
              'position': 'absolute',
              'top': '0',
              'display': 'block',
              'vertical-align': 'middle',
              'background-color': '#000',
              'width': $this.width() + 'px',
              'height': $this.height() + 'px',
              'overflow': 'hidden',
              'display': 'none'
            });
            $('.tumblerImage').find('a').css({
              'height': $this.height() + 'px',
              'display': 'table-cell',
              'vertical-align': 'middle',
              'border': 'none'
            });
            return $this.find('div').eq(0).stop().fadeIn(1000);
          }
        }
      });
    };
    return $this.each(function() {
      jsonLoader();
      addTimer();
      return false;
    });
  };

}).call(this);
